Repository exonet/powerdns-php, pull requests merged in 2021-12, with the labels that each got.

#85 Update default port to 8081
  src/Powerdns.php
  src/PowerdnsInterface.php
Labels: breaking-change

#87 Use variables that make sense in examples
  examples/list_records_for_zone.php
Labels: documentation

#89 Login to docker before pulling containers
  .travis.yml
Labels: ci
