Repository exonet/powerdns-php, pull requests merged in 2022-06, with the labels that each got.

#111 #109 Make package compatible with psr/log 3.0
  composer.json
Labels: dependencies

#112 Added getShortName() method
  src/Resources/ResourceRecord.php
Labels: new-feature

#114 Use GitHub actions and own containers
  .github/workflows/tests.yaml
  .travis.yml
  docker-compose.yml
  run-tests.sh
  src/Resources/ResourceSet.php
  tests/functional/FunctionalTestCase.php
Labels: ci

#113 Add unit test for getShortName
  src/Resources/ResourceRecord.php
  tests/Resources/ResourceRecordTest.php
Labels: skip-changelog
