Repository exonet/powerdns-php, pull requests merged in 2023-02, with the labels that each got.

#128 Add custom connector example
  examples/BasicAuthConnector.php
  examples/custom_connector.php
Labels: skip-changelog

#129 Change the kind of zone
  src/Resources/Zone.php
  src/Transformers/KindTransformer.php
  src/Zone.php
  tests/ZoneTest.php
Labels: new-feature

#130 Accept non-canonical zone name in find
  src/Zone.php
Labels: enhancement

#131 Added example how to add a slave domain
  examples/new_slave_domain.php
Labels: documentation
